### ISSUE TITLE
 Graph_background() doesn't change color

### ISSUE THREAD

**Issue by dbs700** [JohnCoene/grapher#1]
Hi John! Thanks for the lovely graph package. All works fine until I tried to change the background color.
  
R version 3.6.1 
Platform: x86_64-w64-mingw32/x64 (64-bit)

graph(net) %>% 
  graph_background(color="#d3d3d3", .2) %>%
  graph_static_layout() %>%  
  graph_cluster() %>% 
  scale_node_color_coords()

It still produces a black background.

**Comment by JohnCoene** [comment]
Hi Dmitry, I just pushed a fix, you can reinstall and try again. Thanks for reporting this. Feel free to reopen the issue if it does not work.

**Comment by dbs700** [comment]
Thanks, John! I reinstalled it, but unfortunately, it's still the same.

**Comment by JohnCoene** [comment]
Interesting. Your initial example works fine for me.

```r
graph(net) %>%
  graph_background(color="#d3d3d3", .2) %>%
  graph_static_layout() %>%
  graph_cluster() %>%
  scale_node_color_coords()
```

![image](https://user-images.githubusercontent.com/7833796/68762182-f7d17280-0615-11ea-8346-4726b08bd3a8.png)

**Comment by dbs700** [comment]
I assume that this could happen because of some package version difference? Anyways, it works, and it's impressive. Thanks!
